openapi: 3.0.0
info:
  title: Node Mentoring
  description: This is our Node Mentoring.
  version: "1.0"
paths:
  /users/{id}:
    x-swagger-router-controller: controllers
    get:
      operationId: getUserById
      description: Returns users based on ID
      summary: Find user by ID
      parameters:
        - $ref: "#/components/parameters/idPathParameter"
      responses:
        "200":
          description: user response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "500":
          description: error
    delete:
      operationId: deleteUserById
      description: Deletes users based on ID
      summary: Delete user by ID
      parameters:
        - $ref: "#/components/parameters/idPathParameter"
      responses:
        "200":
          description: user deleted
        "404":
          description: user dosn\'t exist

  /group/addUsers:
    x-swagger-router-controller: controllers
    post:
      operationId: addUsersToGroup
      description: add list of users to group
      summary: many users to one group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/usersToGroupBody"
      responses:
        "201":
          description: users added to group
        "400":
          description: error
          content:
            application/json:
              schema:
                type: array

  /group/{id}:
    x-swagger-router-controller: controllers
    get:
      operationId: getGroupById
      description: Returns group based on ID
      summary: Get group by ID
      parameters:
        - $ref: "#/components/parameters/idPathParameter"
      responses:
        "200":
          description: group response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Group"
        "500":
          description: error
    delete:
      operationId: deleteGroupById
      description: Deletes group based on ID
      summary: Delete group by ID
      parameters:
        - $ref: "#/components/parameters/idPathParameter"
      responses:
        "200":
          description: group deleted
        "404":
          description: group dosn\'t exist

  /users:
    x-swagger-router-controller: controllers
    post:
      operationId: createUser
      description: create user
      summary: create user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: user created
        "400":
          description: error
          content:
            application/json:
              schema:
                type: array
    get:
      operationId: gatAllUsers
      description: get all users
      summary: get all users or with setted Limit and Substring
      parameters:
        - in: query
          name: loginSubstring
          schema:
            type: string
          description: The substring of login
        - in: query
          name: limit
          schema:
            type: integer
          description: The limit of users

      responses:
        "200":
          description: all users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
        "400":
          description: all users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
        "500":
          description: all users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
    put:
      operationId: putUser
      description: update or create user
      summary: update or create user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: update or put user
        "400":
          description: error
          content:
            application/json:
              schema:
                type: array

  /groups:
    x-swagger-router-controller: controllers
    post:
      operationId: createGroup
      description: create group
      summary: create group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Group"
      responses:
        "201":
          description: group created
        "400":
          description: error
          content:
            application/json:
              schema:
                type: array
    get:
      operationId: getAllGroups
      description: get all groups
      summary: get all groups or with setted Limit and Substring
      responses:
        "200":
          description: all groups
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Groups"
        "400":
          description: all groups
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Groups"
        "500":
          description: all groups
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Groups"
    put:
      operationId: putGroup
      description: update or create group
      summary: update or create group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Group"
      responses:
        "201":
          description: update or put group
        "400":
          description: error
          content:
            application/json:
              schema:
                type: array

components:
  parameters:
    idPathParameter:
      name: id
      description: user or group id
      example: 1
      in: path
      required: true
      schema:
        type: integer

  schemas:
    usersToGroupBody:
      type: object
      properties:
        usersIds:
          type: array
          items: 
            type: string
        groupId:
          type: string
      required:
        - users
        - group

    User:
      type: object
      properties:
        id:
          oneOf:
            - type: string
            - type: integer
        login:
          type: string
        password:
          type: string
          minLength: 4
          maxLength: 15
          format: password
          pattern: "^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9]).{4,15}$"
        age:
          type: integer
          minimum: 4
          maximum: 140
        isDeleted:
          type: boolean
    Users:
      type: array
      items:
        $ref: "#/components/schemas/User"
    Group:
      type: object
      properties:
        id:
          oneOf:
            - type: string
            - type: integer
        name:
          type: string
        permission:
          type: array
          items:
            type: string
    Groups:
      type: array
      items:
        $ref: "#/components/schemas/Group"
